2021-04-16 12:01:07,305 ERROR: Exception on /buscar [GET] [in c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py:1892]
Traceback (most recent call last):
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\sessions.py", line 378, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\itsdangerous\serializer.py", line 166, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\itsdangerous\url_safe.py", line 42, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\itsdangerous\serializer.py", line 133, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\json\tag.py", line 305, in dumps
    return dumps(self.tag(value), separators=(",", ":"))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'set' is not JSON serializable
2021-04-16 12:01:12,237 ERROR: Request finalizing failed with an error while handling an error [in c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py:1976]
Traceback (most recent call last):
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\sessions.py", line 378, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\itsdangerous\serializer.py", line 166, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\itsdangerous\url_safe.py", line 42, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\itsdangerous\serializer.py", line 133, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\json\tag.py", line 305, in dumps
    return dumps(self.tag(value), separators=(",", ":"))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'set' is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py", line 1970, in finalize_request
    response = self.process_response(response)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\app.py", line 2269, in process_response
    self.session_interface.save_session(self, ctx.session, response)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\sessions.py", line 378, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\itsdangerous\serializer.py", line 166, in dumps
    payload = want_bytes(self.dump_payload(obj))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\itsdangerous\url_safe.py", line 42, in dump_payload
    json = super(URLSafeSerializerMixin, self).dump_payload(obj)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\itsdangerous\serializer.py", line 133, in dump_payload
    return want_bytes(self.serializer.dumps(obj, **self.serializer_kwargs))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\json\tag.py", line 305, in dumps
    return dumps(self.tag(value), separators=(",", ":"))
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\json\__init__.py", line 211, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "c:\users\erezzonico\proyectos\python\borisappfront\env\lib\site-packages\flask\json\__init__.py", line 100, in default
    return _json.JSONEncoder.default(self, o)
  File "c:\users\erezzonico\appdata\local\continuum\anaconda3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'set' is not JSON serializable
2021-04-16 12:06:35,423 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:08:38,103 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:10:22,885 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:10:50,412 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:11:07,300 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:13:40,983 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:24:14,564 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:27:00,147 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:29:37,218 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:32:48,045 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:33:34,485 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:35:59,784 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:36:31,936 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:36:53,606 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:38:59,116 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:40:02,731 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:41:10,800 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
2021-04-16 12:43:13,328 INFO: Boris startup [in C:\Users\erezzonico\Proyectos\Python\BorisAppFront\app\__init__.py:63]
